FROM python:3.10

# Install MDBTools for .mdb → SQL conversion
RUN apt-get update && apt-get install -y mdbtools

WORKDIR /app
COPY . .

RUN pip install --no-cache-dir -r requirements.txt

ENV PORT 10000
CMD ["python", "app.py"]
