# Base image
FROM python:3.10

# Install MDBTools (for Linux)
RUN apt-get update && \
    apt-get install -y mdbtools && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the Flask app
CMD ["python", "app.py"]
